"""
Qwen2.5 Fine-tuning Script — Unsloth + PEFT LoRA
═══════════════════════════════════════════════════

Supervised fine-tuning (SFT) of Qwen2.5-7B-Instruct on parking buddy
conversations generated by build_training_data.py.

Requirements (install when ready to fine-tune):
  pip install unsloth trl datasets accelerate bitsandbytes

Usage:
  # 1. Build the dataset first
  python qwen/finetune/build_training_data.py

  # 2. Run fine-tuning (needs a GPU — 8GB VRAM minimum for 4-bit QLoRA)
  python qwen/finetune/finetune_unsloth.py
  python qwen/finetune/finetune_unsloth.py --model qwen2.5:7b --max-steps 200

  # 3. Export to GGUF for Ollama
  python qwen/finetune/finetune_unsloth.py --export-gguf

After export, create an Ollama Modelfile:
  FROM ./parking_buddy_qwen.gguf
  SYSTEM "You are Parking Buddy..."
  ollama create parking-buddy -f Modelfile

Then set OLLAMA_MODEL_NAME=parking-buddy in .env.
"""

import argparse
import sys
from pathlib import Path

TRAIN_DATA = Path(__file__).resolve().parent.parent.parent / "data" / "finetune" / "train.jsonl"
OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent / "models" / "parking_buddy_qwen"


def run_finetune(model_name: str, max_steps: int, export_gguf: bool):
    """Main fine-tuning routine using Unsloth + TRL SFTTrainer."""
    try:
        from unsloth import FastLanguageModel
        from trl import SFTTrainer, SFTConfig
        from datasets import load_dataset
        import torch
    except ImportError as e:
        print(
            f"[ERROR] Missing fine-tuning dependencies: {e}\n"
            "Run: pip install unsloth trl datasets accelerate bitsandbytes\n"
            "Requires CUDA GPU."
        )
        sys.exit(1)

    if not TRAIN_DATA.exists():
        print(f"[ERROR] Training data not found at {TRAIN_DATA}")
        print("Run: python qwen/finetune/build_training_data.py first")
        sys.exit(1)

    print(f"Loading base model: {model_name}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=2048,
        load_in_4bit=True,       # 4-bit QLoRA — 8GB VRAM sufficient
        dtype=None,
    )

    # ── LoRA adapter config ──────────────────────────────────────────────
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,                    # LoRA rank — increase to 32/64 for more capacity
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=42,
    )
    print(f"LoRA adapter added. Trainable params: {model.num_parameters(only_trainable=True):,}")

    # ── Dataset ──────────────────────────────────────────────────────────
    dataset = load_dataset("json", data_files=str(TRAIN_DATA), split="train")
    print(f"Training dataset: {len(dataset)} examples")

    def format_example(example):
        convs = example["conversations"]
        text = tokenizer.apply_chat_template(
            [{"role": c["from"].replace("human", "user").replace("gpt", "assistant"),
              "content": c["value"]} for c in convs],
            tokenize=False,
            add_generation_prompt=False,
        )
        return {"text": text}

    dataset = dataset.map(format_example)

    # ── Trainer ──────────────────────────────────────────────────────────
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        args=SFTConfig(
            output_dir=str(OUTPUT_DIR),
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=5,
            max_steps=max_steps,
            learning_rate=2e-4,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=42,
            dataset_text_field="text",
            max_seq_length=2048,
        ),
    )
    print(f"Starting fine-tuning for {max_steps} steps...")
    trainer.train()

    # ── Save adapter ─────────────────────────────────────────────────────
    adapter_path = OUTPUT_DIR / "lora_adapter"
    model.save_pretrained(str(adapter_path))
    tokenizer.save_pretrained(str(adapter_path))
    print(f"✓ LoRA adapter saved to {adapter_path}")

    # ── Export to GGUF for Ollama ─────────────────────────────────────────
    if export_gguf:
        gguf_path = OUTPUT_DIR / "parking_buddy_qwen.gguf"
        print(f"Exporting to GGUF: {gguf_path}")
        model.save_pretrained_gguf(
            str(OUTPUT_DIR / "parking_buddy_qwen"),
            tokenizer,
            quantization_method="q4_k_m",
        )
        print(
            f"✓ GGUF export done!\n"
            f"  Create Ollama model:\n"
            f'    echo \'FROM {gguf_path}\' > Modelfile\n'
            f"    ollama create parking-buddy -f Modelfile\n"
            f"  Then set OLLAMA_MODEL_NAME=parking-buddy in .env"
        )


def main():
    parser = argparse.ArgumentParser(description="Fine-tune Qwen2.5 on parking buddy data")
    parser.add_argument("--model", default="unsloth/Qwen2.5-7B-Instruct-bnb-4bit",
                        help="Base model to fine-tune (Unsloth format or HuggingFace ID)")
    parser.add_argument("--max-steps", type=int, default=100,
                        help="Training steps (100 = quick test, 500+ = real training)")
    parser.add_argument("--export-gguf", action="store_true",
                        help="Export merged model to GGUF format for Ollama")
    args = parser.parse_args()
    run_finetune(args.model, args.max_steps, args.export_gguf)


if __name__ == "__main__":
    main()
